// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerService.Data;

#nullable disable

namespace PlayerService.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20251203230912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerService.Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<bool>("IsDrafted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            IsDrafted = false,
                            Name = "Test",
                            Position = "Quarter Back",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            IsDrafted = false,
                            Name = "Test",
                            Position = "Quarter Back",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 3,
                            IsDrafted = false,
                            Name = "Test",
                            Position = "Quarter Back",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 4,
                            IsDrafted = false,
                            Name = "Test",
                            Position = "Quarter Back",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 5,
                            IsDrafted = false,
                            Name = "Test",
                            Position = "Quarter Back",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 6,
                            IsDrafted = false,
                            Name = "Test",
                            Position = "Quarter Back",
                            TeamId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
